In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('cars.csv')

In [6]:
data.head()

                             full_name   name  year  ...  engine  max_power seats
0            Hyundai i20 Sportz Diesel    i20  2010  ...  1396.0      90.00   5.0
1        Hyundai Xcent 1.2 VTVT E Plus  Xcent  2017  ...  1197.0      81.86   5.0
2            Hyundai i20 1.4 CRDi Asta    i20  2012  ...  1396.0      90.00   5.0
3  Hyundai i20 2015-2017 Asta 1.4 CRDi    i20  2016  ...  1396.0      88.73   5.0
4       Hyundai i20 1.2 Asta Dual Tone    i20  2018  ...  1197.0      81.83   5.0

[5 rows x 13 columns]

In [7]:
sample = data.sample(n = 200)

In [9]:
sample.to_csv(r'cars1.csv', index = False)